---
chdir: /Users/cuizheng/Desktop/terminator
environment: production
address: 0.0.0.0
port: 7000
timeout: 30
log: log/production.log
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 512
require: []
wait: 3600
daemonize: true
servers: 2