#!/usr/bin/env ruby
APP_PATH = File.expand_path('../..',  __FILE__)
require File.join(APP_PATH, 'lib/terminator')

require 'irb'
require 'irb/completion'
require "pry"

require 'ruby-debug' if (ENV['RACK_ENV'] == 'development' || ENV['RACK_ENV'] == nil)

binding.pry