#!/usr/bin/env ruby
APP_PATH = File.expand_path('../..',  __FILE__)
require File.join(APP_PATH, 'lib/terminator')

include Terminator::App::Controller
include Terminator::App::Model

require 'irb'
require 'irb/completion'
require "pry"

require 'ruby-debug' if Terminator.env == 'development'

binding.pry